-- AlterTable
ALTER TABLE `leave_balances` MODIFY `leave_type` ENUM('ANNUAL', 'SICK', 'EMERGENCY', 'UNPAID', 'MATERNITY', 'PATERNITY', 'CASUAL', 'RELATIVES_DEATH', 'HAJJ', 'MARRIAGE', 'OTHERS') NOT NULL;

-- AlterTable
ALTER TABLE `leave_requests` MODIFY `leave_type` ENUM('ANNUAL', 'SICK', 'EMERGENCY', 'UNPAID', 'MATERNITY', 'PATERNITY', 'CASUAL', 'RELATIVES_DEATH', 'HAJJ', 'MARRIAGE', 'OTHERS') NOT NULL;
